name: Freeze 
author: Arjun Govindjee
description: Automatically whitelist any online users.
version: 0.3
main: com.carboncraft.freeze.Freeze

commands:
  freeze:
    description: Manage the whitelist. For help type /freeze h
    usage: /freeze [arguments ...]
    permission: freeze.use
    permission-message: ยง4You do not have permission to do that.
